version: '4.1.0'

services:
  medmolnet-front:
    image: medmolnet-frontend
    container_name: medmolnet-frontend
    build:
      context: ./frontend  # Corrected to use context
      dockerfile: Dockerfile  # Corrected to use dockerfile key
    volumes:
      - ./frontend/src:/usr/src/app/src  # Sync local frontend code
    ports:
      - 3000:3000
    networks:
      - medmolnet-beta-network
    environment:
      - REACT_APP_API_URL=http://localhost

  medmolnet-back:
    image: medmolnet-backend
    container_name: medmolnet-backend
    build:
      context: ./backend  # Corrected to use context
      dockerfile: Dockerfile  # Corrected to use dockerfile key
    volumes:
      - ./backend:/python-docker  # Sync local backend code
    networks:
      - medmolnet-beta-network
    ports:
      - 5000:5000
    environment:
      - DB_CONFIG=database.example.ini
    extra_hosts:
    - "host.docker.internal:host-gateway"

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
        - 80:80
    volumes:
        - ./nginx:/etc/nginx
    networks:
      - medmolnet-beta-network

networks:
  medmolnet-beta-network:
    driver: bridge
