name: medmolnet-dev

services:
  frontend:
    image: medmolnet-frontend
    build:
      context: ../../frontend        
      dockerfile: Dockerfile.dev
    volumes:
      - ../../frontend:/usr/src/app   
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - medmolnet-network
    ports:
      - "3000:3000"                  

  backend:
    image: medmolnet-backend
    build:
      context: ..                
      dockerfile: .docker/Dockerfile
    volumes:
      - ..:/python-docker
    working_dir: /python-docker
    command: >
      waitress-serve --host 0.0.0.0 --port 5000 routes:app
    environment:
      - POSTGRES_DB=items
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=+rBGf%p$$BgAX%d+
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432
    depends_on:
      - postgres-db
    networks:
      - medmolnet-network
    # If you want to hit backend directly (without nginx), uncomment:
    # ports:
    #   - "5000:5000"

  postgres-db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_DB=items
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=+rBGf%p$$BgAX%d+   
      - POSTGRES_PORT=5432
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    networks:
      - medmolnet-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "8081:80"                    
    volumes:
      - ../../nginx:/etc/nginx      
      - ../../certbot/conf:/etc/letsencrypt
      - ../../certbot/www:/var/www/certbot
    networks:
      - medmolnet-network
    depends_on:
      - frontend
      - backend

networks:
  medmolnet-network:
    driver: bridge

volumes:
  pgdata:
